JiuzeSite/carts/urls.py
from django.conf.urls import url

from orders.views import user_token
from .views import (
    cart_home,
    cart_update,
    checkout_home,
    checkout_done_view)
app_name = 'carts'
urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^update/$', cart_update, name='update'),
    url(r'^token/', user_token, name='token'),
]

JiuzeSite/products/urls.py
from django.conf.urls import url
from django.urls import path

from products import views
from .views import (
        ProductListView, 
        ProductDetailSlugView, 
        ProductDownloadView
        )
app_name = 'products'
urlpatterns = [
    url(r'^$', ProductListView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/$', ProductDetailSlugView.as_view(), name='detail'),
    url(r'^(?P<slug>[\w-]+)/(?P<pk>\d+)/$', ProductDownloadView.as_view(), name='download'),

]

JiuzeSite/templates/base_dashboard.html
<!doctype html>
<html lang="en">
<head>

  {%load static %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" type="image/x-icon" href="{% static 'Assets/images/stamp.png' %}">

  <title>User Dashboard</title>

  <!-- Bootstrap core CSS -->

  <!-- Custom styles for this template -->
  <link rel="stylesheet" href="{% static 'css/pricing.css' %}">
  <link href="{% static 'Assets/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

  <link href="{% static 'Assets/css/animate.min.css' %}" rel="stylesheet" />

  <link href="{% static 'Assets/fonts/css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'Assets/color/default.css' %}" rel="stylesheet"> 

  <link href="{% static 'Assets/css/animate.min.css' %}" rel="stylesheet" />

  <link href="{% static 'Assets/csss/style.css' %}" rel="stylesheet" type="text/css">

  <link href="{% static 'Assets/color/default.css' %}" rel="stylesheet">
  <!-- Custom styling plus plugins -->
  <link href="{% static 'Assets/css/custom.css' %}" rel="stylesheet">
  <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">




  <link href="{% static 'Assets/fonts/css/font-awesome.min.css' %}" rel="stylesheet">

  <link href="{% static 'Assets/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

  <link href="{% static 'Assets/color/default.css' %}" rel="stylesheet">
  <link href="{% static 'Assets/css4.0/bootstrap.min0.css' %}" rel="stylesheet">
</head>


<body>
 {% url 'home' as home_url %}
 {% url 'contact' as contact_url %}
 {% url 'products:list' as product_list_url %}
 {% url 'login' as login_url %}
 {% url 'producthome' as product_url %}
 {% url 'products: products' as products_url %}
 {% url 'logout' as logout_url %}
 {% url 'register' as register_url %}
 {% url 'signup' as signup_url %}

 {% url 'dashboard' as account_url %}
 {% url 'carts:home' as cart_url %}
 {% url 'about' as about_url %}

 <div class="navbar navbar-expand-md  fixed-top nav-green"  >
  <a class="navbar-brand" href="#">The Market Place</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> 

  <nav class="collapse navbar-collapse" id="navbarsExample04">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active ">
        <a class="nav-link" href="{{ home_url }}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == products_url %} active{% endif%}">
        <a class="nav-link" href="{{ product_url }}">Catalogue</a>
      </li>
      <li class="nav-item {% if request.path == contact_url %}active{% endif %}">
        <a class="nav-link" href="{{contact_url }}">Contact</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item {% if request.path == product_list_url %}active {% endif%}">
        <a class="nav-link" href="{{ product_list_url}}">My DashBoard</a>
      </li>
      <li class="nav-item {% if request.path == about_url %} active{% endif%}">
        <a class="nav-link" href="{{ about_url }}">My Profile</a>
      </li>
      <li class="nav-item {% if request.path == cart_url %} active{% endif%}">
        <a class="nav-link" href="{{ cart_url }}"><i class="fa fa-shopping-cart" aria-hidden="true"></i>{{ request.session.cart_items }}Buy</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ logout_url }}">Sign out</a>
      </li>
      {% else %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">User</a>
        <div class="dropdown-menu" aria-labelledby="dropdown04">
         
         <a class="dropdown-item" href="{{ login_url }}">Login</a>
         <a class="dropdown-item" href="{{ register_url }}">Register</a>


       </div>
     </li>
     {% endif %}
   </ul>
   <form class="form-inline my-2 my-md-0">
    <input class="form-control" type="text" placeholder="Search">
  </form>
</nav>
</div>

<div class="container">

  <div class="row">
    {% if request.user.is_authenticated %}



    <nav class="col-md-2  bg-light sidebar" role="navigation">
      <div class="sidebar-collapse">
        <ul class="nav" id="main-menu">


          <li>
            <a  href="index.html"><i class="fa fa-dashboard "></i>Back To Home Page</a>

          </li>
          <li>
            <a href="index2.html"><i class="fa fa-camera "></i>Products</a>

          </li>
          <li>
            <a href="data-table.html"><i class="fa fa-cloud-download "></i>Product history </a>

          </li>
          


          <li>
            <a href="text-editor.html"><i class="fa fa-dashcube "></i>My Profile</a>
          </li>


          <li>
            <a href="blank.html"><i class="fa fa-table "></i>My Trade Points </a>

          </li>
        </ul>
      </div>

    </nav>





    {% endif %}
    <main role="main" class="col-md-10 ml-sm-auto col-lg-10 pt-2 px-2">
      <div class="col-md-12 col-md-sm col-lg-12">
       <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Dashboard</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
          <div class="btn-group mr-2">
            <button class="btn btn-sm btn-outline-secondary">Share</button>
            <button class="btn btn-sm btn-outline-secondary">Export</button>
          </div>
          <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
            <span data-feather="calendar"></span>
            This week
          </button>
        </div>
      </div>
    </div>
    <div class="col-md-12 col-md-sm col-lg-12">

      {% block content %}

      {% endblock %} 

    </div>
    <div class="col-md-12 col-md-sm col-lg-12">

      <div class="boxx">
        <h2>Sold Products</h2>
        <div class="table-responsive">
          <table class="table table-striped table-sm">
            <thead>
              <tr>
                <th>#</th>
                <th>Customer ID/Token</th>
                <th>Products Purchased</th>
                <th>My Point</th>
                <th>Clients Count</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>1</td>
                <td>rswff5wzorzh</td>
                <td>Casio Original Watch</td>
                <td>6</td>
                <td>5</td>
              </tr>
              <tr>
                <td>2</td>
                <td>rswff5wzorzh</td>
                <td>Casio Original Watch</td>
                <td>6</td>
                <td>5</td>
              </tr>
              <tr>
                <td>3</td>
                <td>rswff5wzorzh</td>
                <td>Casio Original Watch</td>
                <td>6</td>
                <td>5</td>
              </tr>
              <tr>
                <td>4</td>
                <td>rswff5wzorzh</td>
                <td>Casio Original Watch</td>
                <td>6</td>
                <td>5</td>
              </tr>
              <tr>
                <td>5</td>
                <td>rswff5wzorzh</td>
                <td>Casio Original Watch</td>
                <td>6</td>
                <td>5</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

    </div>

  </main>
</div>
</div>








<footer class="footer">
  <div class="container">
   <div class="row">
    <div class="col-md-12 col-lg-12">

      <p>©2018 All Rights Reserved <i class="fa fa-user" >Thornelloyd Computers  service Gen .Ltd</i>. Privacy and Terms</p>
                    <!--
                        All links in the footer should remain intact.
                        Licenseing information is available at: http://bootstraptaste.com/license/
                        You can buy this theme without footer links online at: http://bootstraptaste.com/buy/?theme=Squadfree
                      -->
                    </div>
                  </div>
                </div>
              </footer>


    <!-- Bootstrap core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="{% static 'js/jquery-slim.min.js' %}"><\/script>')</script>
      <script src="{% static 'js/popper.min.js' %}"></script>
      <script src="{% static 'Assets/jsb4.0/bootstrap.min.js' %}"></script>

      <!-- Icons -->
      <script src="https://unpkg.com/feather-icons/dist/feather.min.js' %}"></script>
      <script>
        feather.replace()
      </script>

      <!-- Graphs -->
      <script src="{% static 'Assets/js/chartjs/chart.min.js' %}"></script>
      <script src="{% static 'Assets/jsss/jquery.min.js '%}"></script>
      <script src="{% static 'Assets/jsss/bootstrap.min.js '%}"></script>
      <script src="{% static 'Assets/jsss/jquery.easing.min.js '%}"></script>
      <script src="{% static 'Assets/jsss/jquery.scrollTo.js '%}"></script>
      <script src="{% static 'Assets/jsss/wow.min.js '%}"></script>

      <!-- Custom Theme JavaScript -->
      <script src="{% static 'Assets/jsss/custom.js '%}"></script>
      <script src="{% static 'js/custom.js '%}"></script>
      <script src="{% static 'js/jquery-1.11.1.js '%}"></script>
      <script src="{% static 'js/bootstrap.js '%}"></script>

      <script src="{% static 'js/jquery.metisMenu.js '%}"></script>

      <script>
        var ctx = document.getElementById("myChart");
        var myChart = new Chart(ctx, {
          type: 'line',
          data: {
            labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
            datasets: [{
              data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
              lineTension: 0,
              backgroundColor: 'transparent',
              borderColor: '#007bff',
              borderWidth: 4,
              pointBackgroundColor: '#007bff'
            }]
          },
          options: {
            scales: {
              yAxes: [{
                ticks: {
                  beginAtZero: false
                }
              }]
            },
            legend: {
              display: false,
            }
          }
        });
      </script>
      <!-- Custom Theme JavaScript -->
      <script src="{% static 'Assets/jsss/custom.js '%}"></script>
      <style type="text/css">






    </style>

  </body>
  </html>

JiuzeSite/templates/contact.html
{% extends 'acc_temp/base.html' %}




{% block content %}
{%load staticfiles %} 
  <div class="container">

   <div class="row">
    <div class="col-lg-2 col-lg-offset-5">
     <hr class="marginbot-50">
   </div>
 </div>
 <div class="row">
  <div class="col-lg-8">
    <form id="contact-form" action="" method="post">
     <div class="row">
    <div class='row'>
        <div class='col-12 col-md-6'>
                <h1>{{ object.title }}</h1>
                {{ object.timestamp|timesince }} ago
                {{ object.description|linebreaks }}<br/>
                {% if object.image %}
                    <img src='{{ object.image.url }}' class='img-fluid' />
                {% endif %}
        </div>
        <div class='col-12 col-md-6'>
            {% include 'products/snippets/update-cart.html' with product=object cart=cart %}

        </div>
</div>
</div>
</form>
</div>

<div class="col-lg-4">
 <div class="widget-contact">
  <h5>Me-TechGlobal inc.</h5>

  <address>
   <strong>Me-TechGlobal .inc</strong><br>
   Daniel K. Tanui<br>
   Developer<br>
   <abbr title="Phone"></abbr> +(254) 729-827 683
 </address>

 <address>
   <strong>Visit us @www.info.metechglobal.co.ke</strong><br>
   <a href="mailto:#">info@metechglobal.co.ke</a><br>
   <a href="mailto:#">histerdans14@gmail.com</a><br>
   <a href="mailto:#">daniel.ktanui14@gmail.com</a>
 </address>
 <address>
   <strong>We're on social networks</strong><br>
   <ul class="company-social">
    <li class="social-facebook"><a href="#" target="_blank"><i class="fa fa-facebook"></i></a></li>
    <li class="social-twitter"><a href="#" target="_blank"><i class="fa fa-twitter"></i></a></li>
    <li class="social-dribble"><a href="#" target="_blank"><i class="fa fa-dribbble"></i></a></li>
    <li class="social-google"><a href="#" target="_blank"><i class="fa fa-google-plus"></i></a></li>
  </ul>
</address>

</div>
</div>
</div>

</div>

{% endblock %}}

JiuzeSite/templates/home_page.html
{% extends "base_dashboard.html" %}
{% load static %}

<title>Home Page Template</title>

{% block base_head %}
<link href="{% static 'Assets/csss/bootstrap.min.css' %}" rel="stylesheet" type="text/css">

          <!-- Fonts -->
          <link href="{% static 'Assets/fonts/css/font-awesome.min.css' %}" rel="stylesheet">
          <link rel="shortcut icon" type="image/x-icon" href="{% static 'Assets/images/stamp.png' %}">
          <link href="{% static 'Assets/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

          <link href="{% static 'Assets/css/animate.min.css' %}" rel="stylesheet" />
          <!-- Squad theme CSS -->
          <link href="{% static 'Assets/csss/style.css' %}" rel="stylesheet" type="text/css">
          <link href="{% static 'Assets/color/default.css' %}" rel="stylesheet">



          <!-- Bootstrap core CSS -->

          <link href="{% static 'Assets/css/bootstrap.min.css' %}" rel="stylesheet">

          <link href="{% static 'Assets/fonts/css/font-awesome.min.css' %}" rel="stylesheet">
          <link href="{% static 'Assets/css/animate.min.css' %}" rel="stylesheet">

          <!-- Custom styling plus plugins -->
          <link href="{% static 'Assets/css/custom.css' %}" rel="stylesheet">
          <link href="{% static 'Assets/css/icheck/flat/green.css' %}" rel="stylesheet">
          <link rel="shortcut icon" type="image/x-icon" href="{% static 'Assets/images/stamp.png' %}">


          <script src="{% static 'Assets/js/jquery.min.js' %}"></script>

          <!--[if lt IE 9]-->
          <script src="{% static 'Assets/js/ie8-responsive-file-warning.js' %}"></script>
          <!--[endif]-->

{% endblock %}

{% block content %}
<div class='text-center'>
    <h1>{{ title }}</h1>
    <h1>Hello, world we're working!</h1>
</div>

<div class='row'>
  <div class='col'>
      <img src="{% static 'img/beach.jpg' %}" class='img-fluid' />
      <p>{{ content }}</p>
  </div>
</div>
{% if request.user.is_authenticated %}
<div class='row'>
  <div class='col'>
  <h1>Premium</h1>
  {{ premium_content }}
  </div>
</div>
{% endif %}


{% endblock %}

<!DOCTYPE html>
    <html lang="en">
    <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <!-- Bootstrap CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
      <link rel='stylesheet' href='{% static "css/main.css" %}' >
    </head>
    <body>
      <div class='text-center'>
          <h1>{{ title }}</h1>
          <h1>Hello, world we're working!</h1>
      </div>
      <div class='container'>
        <div class='row'>
          <div class='col'>
              <img src="{% static 'img/beach.jpg' %}" class='img-fluid' />
              <p>{{ content }}</p>
          </div>
        </div>
        {% if request.user.is_authenticated %}
        <div class='row'>
          <div class='col'>
          <h1>Premium</h1>
          {{ premium_content }}
          </div>
        </div>
        {% endif %}
      </div>
      <!-- Optional JavaScript -->
      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
    </body>
  </html>

JiuzeSite/templates/login.html
  {% extends 'acc_temp/base.html' %}

  {% block content %}


  {%load static %}




  <link href="{% static 'sales_sta/Assets/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'sales_sta/Assets/signin.css' %}" rel="stylesheet">
  
  <div class="container text-center">


   <div class="row">
    <div class="col-lg-8">
     <div class="boxed-grey">
      <form id="contact-form" action="{% url 'login' %}" method="POST" enctype="multipart/form-data">{% csrf_token %}


       <div class="row">
        <img class="mb-4" src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <label for="email" class="sr-only">Email address</label>
        <input type="email" id="email" name="email" class="form-control" placeholder="Email address" required autofocus>
        <label for="password" class="sr-only">Password</label>
        <input type="password" id="password" name="password" class="form-control" placeholder="Password" required>
        <div class="checkbox mb-3">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit" >Sign in</button>
        <div   class="row">
          <p>{{error}}</p>
        </div>
        <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>

      </div>
    </form>
  </div>
</div>

<div class="col-lg-4">
 <div class="widget-contact">
  <h5>Me-TechGlobal Ltd.</h5>

  <address>
   <strong>Me-TechGlobal Ltd.</strong><br>
   Daniel K. Tanui<br>
   Developer<br>
   <abbr title="Phone"></abbr> +(254) 729-827 683
 </address>

 <address>
   <strong>Visit us @www.info.metechglobal.co.ke</strong><br>
   <a href="mailto:#">info@metechglobal.co.ke</a><br>
   <a href="mailto:#">histerdans14@gmail.com</a><br>
   <a href="mailto:#">daniel.ktanui14@gmail.com</a>
 </address>
 <address>
   <strong>We're on social networks</strong><br>
   <ul class="company-social">
    <li class="social-facebook"><a href="#" target="_blank"><i class="fa fa-facebook"></i></a></li>
    <li class="social-twitter"><a href="#" target="_blank"><i class="fa fa-twitter"></i></a></li>
    <li class="social-dribble"><a href="#" target="_blank"><i class="fa fa-dribbble"></i></a></li>
    <li class="social-google"><a href="#" target="_blank"><i class="fa fa-google-plus"></i></a></li>
  </ul>
</address>

</div>
</div>
</div>

</div>

{% endblock %}}

JiuzeSite/templates/sessions.html
{% block content %}
 
    {% if username is None %}
        <form role="form" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" value="Submit" class="btn btn-info">LogIn</button>
        </form>
    {% else %}
        <h3>Welcome you are signed in as {{ username }}</h3>
        <a href="{% url "demos-sessions" %}?action=logout">LogOut</a>
    {% endif %}
 
{% endblock %}